version: '3.8'
services:
  db:
    container_name: mariadb
    image: mariadb
    env_file: [.env]
    networks: [domserver-network]
    restart: unless-stopped
    volumes:
      - ./database/:/var/lib/mysql/
    command: --max-connections=1000
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8081:80
    networks: [domserver-network]
    restart: unless-stopped
  domserver:
    container_name: domserver
    image: zydhanlinnar11/alpro-domjudge:main
    env_file: [.env]
    ports:
      - 8080:80
    networks: [domserver-network]
    restart: unless-stopped
    depends_on:
      - db
  judgehost_core0:
    container_name: judgehost_core0
    image: domjudge/judgehost:8.0.0
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=0
      - DOMSERVER_BASEURL=http://domserver/

networks:
  domserver-network:
