version: '3.8'
services:
  db:
    container_name: mariadb
    image: mariadb
    env_file: [.env]
    networks: [domserver-network]
    restart: unless-stopped
    volumes:
      - ./database/:/var/lib/mysql/
    command: --max-connections=1000 --max-allowed-packet=512M
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8081:80
    networks: [domserver-network]
    restart: unless-stopped
  domserver:
    container_name: domserver
    image: zydhanlinnar11/alpro-domjudge:main
    env_file: [.env]
    ports:
      - 80:80
    networks: [domserver-network]
    volumes:
      - ./public:/opt/domjudge/domserver/webapp/public
      - ./domserver/domjudge-inner:/etc/nginx/snippets/domjudge-inner
    restart: unless-stopped
    depends_on:
      - db
  judgehost_core0:
    container_name: judgehost_core0
    image: domjudge/judgehost:latest
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=0
      - DOMSERVER_BASEURL=http://domserver/
  judgehost_core1:
    container_name: judgehost_core1
    image: domjudge/judgehost:latest
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=1
      - DOMSERVER_BASEURL=http://domserver/
  judgehost_core2:
    container_name: judgehost_core2
    image: domjudge/judgehost:latest
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=2
      - DOMSERVER_BASEURL=http://domserver/
  judgehost_core3:
    container_name: judgehost_core3
    image: domjudge/judgehost:latest
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=3
      - DOMSERVER_BASEURL=http://domserver/
  judgehost_core4:
    container_name: judgehost_core4
    image: domjudge/judgehost:latest
    env_file: [.env]
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    hostname: judgehost-alpro-main
    restart: unless-stopped
    networks: [domserver-network]
    environment:
      - DAEMON_ID=4
      - DOMSERVER_BASEURL=http://domserver/

networks:
  domserver-network:
    driver: bridge
